version: '3'
services:
  load-balancer:
    ports:
      - '3000:80'
  server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./dev.env
    command: npm run dev
  database:
    env_file:
      - ./dev.env
