version: "3"
services:
  server:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "4000:5000"
    env_file:
      - ./prod.env
    command: npm run start
  database:
    env_file:
      - ./prod.env