version: "3"
services:
  server:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./dev.env
    command: npm run dev
  database:
    env_file:
      - ./dev.env
