version: '3'
services:
  load-balancer:
    ports:
      - '80:80'
  server:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./prod.env
    command: npm run start
  database:
    env_file:
      - ./prod.env
