version: '3'
services:
  load-balancer:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  server:
    build: .
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - mongo-db:/data/db
  cache:
    image: redis
volumes:
  mongo-db:
